# Generated by Django 5.2.4 on 2025-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('index', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('trend', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('pl', models.FloatField()),
                ('brokerage', models.FloatField()),
                ('charges', models.FloatField()),
                ('net_pl', models.FloatField()),
            ],
        ),
    ]
